ntp_servers:
  - ntp1.vniiftri.ru
  - ntp2.vniiftri.ru
  - ntp3.vniiftri.ru
  - 0.asia.pool.ntp.org
  - 1.asia.pool.ntp.org
  - 2.asia.pool.ntp.org
  - 3.asia.pool.ntp.org

moodle_domain: moodle.au-team.irpo
wiki_domain: wiki.au-team.irpo