---
- name: Установка mdadm
  apt:
    name: mdadm
    state: present

- name: Обнуление метаданных дисков
  command: mdadm --zero-superblock --force /dev/sdb /dev/sdc /dev/sdd
  when: raid_disks is defined and raid_disks | length > 0

- name: Создание RAID5 массива
  command: mdadm --create --verbose /dev/md0 --level=5 --raid-devices=3 /dev/sdb /dev/sdc /dev/sdd

- name: Создание файла mdadm.conf
  block:
    - file:
        path: /etc/mdadm/mdadm.conf
        state: touch
    - lineinfile:
        path: /etc/mdadm/mdadm.conf
        line: "DEVICE partitions"
    - command: mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf

- name: Создание файловой системы на RAID5
  filesystem:
    fstype: ext4
    device: /dev/md0

- name: Создание точки монтирования
  file:
    path: /etc/raid5
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Монтирование RAID5 массива
  mount:
    path: /etc/raid5
    src: /dev/md0
    fstype: ext4
    state: mounted

- name: Добавление записи в /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ raid_uuid }} /etc/raid5 ext4 defaults 0 0"
    create: yes
  vars:
    raid_uuid: "{{ ansible_mounts | selectattr('device', 'equalto', '/dev/md0') | first | attr('uuid') }}"