---
- name: Установка NFS сервера
  apt:
    name: nfs-kernel-server
    state: present

- name: Создание директории для экспорта
  file:
    path: /etc/raid5/nfs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Настройка файла exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'

- name: Перезапуск службы NFS
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes

- name: Экспорт NFS
  shell: exportfs -a